from .dashboard import DashboardAdmin
from .produtos import ProdutosAdmin
from .categorias import CategoriasAdmin
from .estoque import EstoqueAdmin
from .pedidos import PedidosAdmin
from .clientes import ClientesAdmin
from .financeiro import FinanceiroAdmin
from .pix import PixAdmin
from .gateway import GatewayAdmin
from .cupons import CuponsAdmin
from .promocoes import PromocoesAdmin
from .afiliados import AfiliadosAdmin
from .mensagens import MensagensAdmin
from .botoes import BotoesAdmin
from .menus import MenusAdmin
from .banners import BannersAdmin
from .temas import TemasAdmin
from .aparencia import AparenciaAdmin
from .permissoes import PermissoesAdmin
from .webhooks import WebhooksAdmin
from .relatorios import RelatoriosAdmin
from .notificacoes import NotificacoesAdmin
from .logs import LogsAdmin
from .auditoria import AuditoriaAdmin
from .backup import BackupAdmin
from .config import ConfigAdmin
